// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/spaceearthbk.tga
gfx/env/spaceearthdn.tga
gfx/env/spaceearthft.tga
gfx/env/spaceearthlf.tga
gfx/env/spaceearthrt.tga
gfx/env/spaceearthup.tga
models/shl/hev_sci.mdl
models/shl/race.mdl
models/shl/weapons/p_768mmvulcan.mdl
models/shl/weapons/p_p904.mdl
models/shl/weapons/p_plasmagun.mdl
models/shl/weapons/v_768mmvulcan.mdl
models/shl/weapons/v_p904.mdl
models/shl/weapons/v_plasmagun.mdl
models/shl/weapons/w_768ammo.mdl
models/shl/weapons/w_768mmvulcan.mdl
models/shl/weapons/w_p904.mdl
models/shl/weapons/w_plasmaclip.mdl
models/shl/weapons/w_plasmagun.mdl
shl.wad
sound/shl/alarm.wav
sound/shl/dbarrel1.wav
sound/shl/hevbarney/hks1.wav
sound/shl/hevbarney/hks2.wav
sound/shl/hevbarney/hks3.wav
sound/shl/hevbarney/sbarrel1.wav
sound/shl/hevbarney/scock1.wav
sound/shl/hevsci/run1.wav
sound/shl/m41a_3round.wav
sound/shl/m41a_single.wav
sound/shl/m41aglauncher.wav
sound/shl/m41aglauncher2.wav
sound/shl/nuke_explode.wav
sound/shl/race/race_alert1.wav
sound/shl/race/race_alert2.wav
sound/shl/race/race_die1.wav
sound/shl/race/race_die2.wav
sound/shl/race/race_idle1.wav
sound/shl/race/race_idle2.wav
sound/shl/race/race_idle3.wav
sound/shl/race/race_idle4.wav
sound/shl/race/race_pain1.wav
sound/shl/race/race_pain2.wav
sound/shl/race/race_pain3.wav
sound/shl/race/race_pain4.wav
sound/shl/race/race_pain5.wav
sound/shl/scientist/shl2_sci_go.wav
sound/shl/scientist/shl2_sci_goingon.wav
sound/shl/scientist/shl2_sci_here.wav
sound/shl/scientist/shl6_sci_outofhere.wav
sound/shl/scientist/shl9_sci_destroy.wav
sound/shl/scientist/shl9_sci_reactor.wav
sound/shl/scientist/shl_ship_conquerearth.wav
sound/shl/scientist/shl_ship_destroyship.wav
sound/shl/scientist/shl_ship_findyourway.wav
sound/shl/scientist/shl_ship_mothership.wav
sound/shl/scientist/shl_ship_otherhumans.wav
sound/shl/scientist/shl_ship_rescuethem.wav
sound/shl/scientist/shl_ship_stopthem.wav
sound/shl/scientist/shlwork_sample.wav
sound/shl/sf1.wav
sound/shl/sf2.wav
sound/shl/sf5.wav
sound/shl/spf_reload1.wav
sound/shl/ufobeam.wav
sound/shl/ufobeam2.wav
sound/shl/weapons/hw_spin.wav
sound/shl/weapons/hw_spindown.wav
sound/shl/weapons/hw_spinup.wav
sound/shl/weapons/m16burst.wav
sound/shl/weapons/p904_reload1.wav
sound/shl/weapons/p904_reload2.wav
sound/shl/weapons/plasma1.wav
sound/shl/weapons/plasma2.wav
sound/shl/weapons/plasma_re.wav
sprites/shl/weapons/640shl1.spr
sprites/shl/weapons/640shl2.spr
sprites/shl/weapons/640shl3.spr
sprites/shl/weapons/640shl4.spr
sprites/shl/weapons/plasma.spr
sprites/shl/weapons/plasmasmall.spr
sprites/shl/weapons/weapon_P904.txt
sprites/shl/weapons/weapon_plasma.txt
sprites/shl/weapons/weapon_vulcan.txt
