// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/spaceearthbk.tga
gfx/env/spaceearthdn.tga
gfx/env/spaceearthft.tga
gfx/env/spaceearthlf.tga
gfx/env/spaceearthrt.tga
gfx/env/spaceearthup.tga
models/shl/probeboss.mdl
models/shl/weapons/p_768mmvulcan.mdl
models/shl/weapons/p_p904.mdl
models/shl/weapons/p_plasmagun.mdl
models/shl/weapons/v_768mmvulcan.mdl
models/shl/weapons/v_p904.mdl
models/shl/weapons/v_plasmagun.mdl
models/shl/weapons/w_768ammo.mdl
models/shl/weapons/w_768mmvulcan.mdl
models/shl/weapons/w_p904.mdl
models/shl/weapons/w_plasmaclip.mdl
models/shl/weapons/w_plasmagun.mdl
shl.wad
sound/shl/2001.wav
sound/shl/B3_00002.wav
sound/shl/dinner.wav
sound/shl/laser.wav
sound/shl/monoris.wav
sound/shl/probeboss/active.wav
sound/shl/sf3.wav
sound/shl/sf4.wav
sound/shl/shl_se1.wav
sound/shl/shl_se1b.wav
sound/shl/shl_se2.wav
sound/shl/shl_se5.wav
sound/shl/ufo_alarm.wav
sound/shl/ufo_boss.wav
sound/shl/weapons/hw_spin.wav
sound/shl/weapons/hw_spindown.wav
sound/shl/weapons/hw_spinup.wav
sound/shl/weapons/m16burst.wav
sound/shl/weapons/p904_reload1.wav
sound/shl/weapons/p904_reload2.wav
sound/shl/weapons/plasma1.wav
sound/shl/weapons/plasma2.wav
sound/shl/weapons/plasma_re.wav
sprites/shl/weapons/640shl1.spr
sprites/shl/weapons/640shl2.spr
sprites/shl/weapons/640shl3.spr
sprites/shl/weapons/640shl4.spr
sprites/shl/weapons/plasma.spr
sprites/shl/weapons/plasmasmall.spr
sprites/shl/weapons/weapon_P904.txt
sprites/shl/weapons/weapon_plasma.txt
sprites/shl/weapons/weapon_vulcan.txt
