// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/shl/hev_sci.mdl
models/shl/hevsci.mdl
models/shl/weapons/p_768mmvulcan.mdl
models/shl/weapons/p_p904.mdl
models/shl/weapons/p_plasmagun.mdl
models/shl/weapons/v_768mmvulcan.mdl
models/shl/weapons/v_p904.mdl
models/shl/weapons/v_plasmagun.mdl
models/shl/weapons/w_768ammo.mdl
models/shl/weapons/w_768mmvulcan.mdl
models/shl/weapons/w_p904.mdl
models/shl/weapons/w_plasmaclip.mdl
models/shl/weapons/w_plasmagun.mdl
shl.wad
sound/shl/dbarrel1.wav
sound/shl/hevbarney/hks1.wav
sound/shl/hevbarney/hks2.wav
sound/shl/hevbarney/hks3.wav
sound/shl/hevbarney/sbarrel1.wav
sound/shl/hevbarney/scock1.wav
sound/shl/hevsci/run1.wav
sound/shl/jazz2.wav
sound/shl/m41a_3round.wav
sound/shl/m41a_single.wav
sound/shl/m41aglauncher.wav
sound/shl/m41aglauncher2.wav
sound/shl/next_st.wav
sound/shl/shl_materials.txt
sound/shl/spf_reload1.wav
sound/shl/weapons/hw_spin.wav
sound/shl/weapons/hw_spindown.wav
sound/shl/weapons/hw_spinup.wav
sound/shl/weapons/m16burst.wav
sound/shl/weapons/p904_reload1.wav
sound/shl/weapons/p904_reload2.wav
sound/shl/weapons/plasma1.wav
sound/shl/weapons/plasma2.wav
sound/shl/weapons/plasma_re.wav
sprites/shl/weapons/640shl1.spr
sprites/shl/weapons/640shl2.spr
sprites/shl/weapons/640shl3.spr
sprites/shl/weapons/640shl4.spr
sprites/shl/weapons/plasma.spr
sprites/shl/weapons/plasmasmall.spr
sprites/shl/weapons/weapon_P904.txt
sprites/shl/weapons/weapon_plasma.txt
sprites/shl/weapons/weapon_vulcan.txt
