// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/shl/hev_sci.mdl
models/shl/race.mdl
models/shl/w_xenmedkit.mdl
models/shl/weapons/p_768mmvulcan.mdl
models/shl/weapons/p_p904.mdl
models/shl/weapons/p_plasmagun.mdl
models/shl/weapons/v_768mmvulcan.mdl
models/shl/weapons/v_p904.mdl
models/shl/weapons/v_plasmagun.mdl
models/shl/weapons/w_768ammo.mdl
models/shl/weapons/w_768mmvulcan.mdl
models/shl/weapons/w_p904.mdl
models/shl/weapons/w_plasmaclip.mdl
models/shl/weapons/w_plasmagun.mdl
shl.wad
sound/shl/bigdoor.wav
sound/shl/bom.wav
sound/shl/cube.wav
sound/shl/dbarrel1.wav
sound/shl/doing.wav
sound/shl/fear1.wav
sound/shl/hahaha.wav
sound/shl/hevbarney/hks1.wav
sound/shl/hevbarney/hks2.wav
sound/shl/hevbarney/hks3.wav
sound/shl/hevbarney/sbarrel1.wav
sound/shl/hevbarney/scock1.wav
sound/shl/hevsci/run1.wav
sound/shl/m41a_3round.wav
sound/shl/m41a_single.wav
sound/shl/m41aglauncher.wav
sound/shl/m41aglauncher2.wav
sound/shl/nuke_explode.wav
sound/shl/pico.wav
sound/shl/pkup.wav
sound/shl/race/race_alert1.wav
sound/shl/race/race_alert2.wav
sound/shl/race/race_die1.wav
sound/shl/race/race_die2.wav
sound/shl/race/race_idle1.wav
sound/shl/race/race_idle2.wav
sound/shl/race/race_idle3.wav
sound/shl/race/race_idle4.wav
sound/shl/race/race_pain1.wav
sound/shl/race/race_pain2.wav
sound/shl/race/race_pain3.wav
sound/shl/race/race_pain4.wav
sound/shl/race/race_pain5.wav
sound/shl/radio.wav
sound/shl/set.wav
sound/shl/ship1.wav
sound/shl/shock_discharge.wav
sound/shl/small.wav
sound/shl/spf_reload1.wav
sound/shl/ufo_bgm.wav
sound/shl/ufo_on.wav
sound/shl/vivaldi1.wav
sound/shl/weapons/hw_spin.wav
sound/shl/weapons/hw_spindown.wav
sound/shl/weapons/hw_spinup.wav
sound/shl/weapons/m16burst.wav
sound/shl/weapons/p904_reload1.wav
sound/shl/weapons/p904_reload2.wav
sound/shl/weapons/plasma1.wav
sound/shl/weapons/plasma2.wav
sound/shl/weapons/plasma_re.wav
sound/shl/xensound0.wav
sprites/shl/weapons/640shl1.spr
sprites/shl/weapons/640shl2.spr
sprites/shl/weapons/640shl3.spr
sprites/shl/weapons/640shl4.spr
sprites/shl/weapons/plasma.spr
sprites/shl/weapons/plasmasmall.spr
sprites/shl/weapons/weapon_P904.txt
sprites/shl/weapons/weapon_plasma.txt
sprites/shl/weapons/weapon_vulcan.txt
