// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/shl/hev_sci.mdl
models/shl/hevsci.mdl
models/shl/race.mdl
models/shl/weapons/p_768mmvulcan.mdl
models/shl/weapons/p_p904.mdl
models/shl/weapons/p_plasmagun.mdl
models/shl/weapons/v_768mmvulcan.mdl
models/shl/weapons/v_p904.mdl
models/shl/weapons/v_plasmagun.mdl
models/shl/weapons/w_768ammo.mdl
models/shl/weapons/w_768mmvulcan.mdl
models/shl/weapons/w_p904.mdl
models/shl/weapons/w_plasmaclip.mdl
models/shl/weapons/w_plasmagun.mdl
shl.wad
sound/shl/code.ogg
sound/shl/dbarrel1.ogg
sound/shl/hevbarney/hks1.ogg
sound/shl/hevbarney/hks2.ogg
sound/shl/hevbarney/hks3.ogg
sound/shl/hevbarney/sbarrel1.ogg
sound/shl/hevbarney/scock1.ogg
sound/shl/hevsci/run1.ogg
sound/shl/m41a_3round.ogg
sound/shl/m41a_single.ogg
sound/shl/m41aglauncher.ogg
sound/shl/m41aglauncher2.ogg
sound/shl/race/race_alert1.ogg
sound/shl/race/race_alert2.ogg
sound/shl/race/race_die1.ogg
sound/shl/race/race_die2.ogg
sound/shl/race/race_idle1.ogg
sound/shl/race/race_idle2.ogg
sound/shl/race/race_idle3.ogg
sound/shl/race/race_idle4.ogg
sound/shl/race/race_pain1.ogg
sound/shl/race/race_pain2.ogg
sound/shl/race/race_pain3.ogg
sound/shl/race/race_pain4.ogg
sound/shl/race/race_pain5.ogg
sound/shl/scientist/shl2_sci_go.ogg
sound/shl/scientist/shl2_sci_goingon.ogg
sound/shl/scientist/shl2_sci_here.ogg
sound/shl/scientist/shl6_sci_outofhere.ogg
sound/shl/scientist/shl9_sci_destroy.ogg
sound/shl/scientist/shl9_sci_reactor.ogg
sound/shl/scientist/shl_ship_conquerearth.ogg
sound/shl/scientist/shl_ship_destroyship.ogg
sound/shl/scientist/shl_ship_findyourway.ogg
sound/shl/scientist/shl_ship_mothership.ogg
sound/shl/scientist/shl_ship_otherhumans.ogg
sound/shl/scientist/shl_ship_rescuethem.ogg
sound/shl/scientist/shl_ship_stopthem.ogg
sound/shl/scientist/shlwork_sample.ogg
sound/shl/shl_materials.txt
sound/shl/shlloop4.ogg
sound/shl/spf_reload1.ogg
sound/shl/ufo.ogg
sound/shl/ufo_bgm.ogg
sound/shl/ufobeam.ogg
sound/shl/weapons/hw_spin.ogg
sound/shl/weapons/hw_spindown.ogg
sound/shl/weapons/hw_spinup.ogg
sound/shl/weapons/m16burst.ogg
sound/shl/weapons/p904_reload1.ogg
sound/shl/weapons/p904_reload2.ogg
sound/shl/weapons/plasma1.ogg
sound/shl/weapons/plasma2.ogg
sound/shl/weapons/plasma_re.ogg
sprites/gst/extra.spr
sprites/gst/spritefont1.spr
sprites/shl/weapons/640shl1.spr
sprites/shl/weapons/640shl2.spr
sprites/shl/weapons/640shl3.spr
sprites/shl/weapons/640shl4.spr
sprites/shl/weapons/plasma.spr
sprites/shl/weapons/plasmasmall.spr
sprites/shl/weapons/weapon_P904.txt
sprites/shl/weapons/weapon_plasma.txt
sprites/shl/weapons/weapon_vulcan.txt
