// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/spaceearthbk.tga
gfx/env/spaceearthdn.tga
gfx/env/spaceearthft.tga
gfx/env/spaceearthlf.tga
gfx/env/spaceearthrt.tga
gfx/env/spaceearthup.tga
models/shl/probeboss.mdl
models/shl/weapons/p_768mmvulcan.mdl
models/shl/weapons/p_p904.mdl
models/shl/weapons/p_plasmagun.mdl
models/shl/weapons/v_768mmvulcan.mdl
models/shl/weapons/v_p904.mdl
models/shl/weapons/v_plasmagun.mdl
models/shl/weapons/w_768ammo.mdl
models/shl/weapons/w_768mmvulcan.mdl
models/shl/weapons/w_p904.mdl
models/shl/weapons/w_plasmaclip.mdl
models/shl/weapons/w_plasmagun.mdl
shl.wad
sound/shl/2001.ogg
sound/shl/B3_00002.ogg
sound/shl/dinner.ogg
sound/shl/laser.ogg
sound/shl/monoris.ogg
sound/shl/probeboss/active.ogg
sound/shl/scientist/shl2_sci_go.ogg
sound/shl/scientist/shl2_sci_goingon.ogg
sound/shl/scientist/shl2_sci_here.ogg
sound/shl/scientist/shl6_sci_outofhere.ogg
sound/shl/scientist/shl9_sci_destroy.ogg
sound/shl/scientist/shl9_sci_reactor.ogg
sound/shl/scientist/shl_ship_conquerearth.ogg
sound/shl/scientist/shl_ship_destroyship.ogg
sound/shl/scientist/shl_ship_findyourway.ogg
sound/shl/scientist/shl_ship_mothership.ogg
sound/shl/scientist/shl_ship_otherhumans.ogg
sound/shl/scientist/shl_ship_rescuethem.ogg
sound/shl/scientist/shl_ship_stopthem.ogg
sound/shl/scientist/shlwork_sample.ogg
sound/shl/sf3.ogg
sound/shl/sf4.ogg
sound/shl/shl_materials.txt
sound/shl/shl_se1.ogg
sound/shl/shl_se1b.ogg
sound/shl/shl_se2.ogg
sound/shl/shl_se5.ogg
sound/shl/ufo_alarm.ogg
sound/shl/ufo_boss.ogg
sound/shl/weapons/hw_spin.ogg
sound/shl/weapons/hw_spindown.ogg
sound/shl/weapons/hw_spinup.ogg
sound/shl/weapons/m16burst.ogg
sound/shl/weapons/p904_reload1.ogg
sound/shl/weapons/p904_reload2.ogg
sound/shl/weapons/plasma1.ogg
sound/shl/weapons/plasma2.ogg
sound/shl/weapons/plasma_re.ogg
sprites/gst/extra.spr
sprites/gst/spritefont1.spr
sprites/shl/weapons/640shl1.spr
sprites/shl/weapons/640shl2.spr
sprites/shl/weapons/640shl3.spr
sprites/shl/weapons/640shl4.spr
sprites/shl/weapons/plasma.spr
sprites/shl/weapons/plasmasmall.spr
sprites/shl/weapons/weapon_P904.txt
sprites/shl/weapons/weapon_plasma.txt
sprites/shl/weapons/weapon_vulcan.txt
